In [2]:
import numpy as np

a = np.random.randn(5)

In [12]:
print(a)

[ 0.17490732 -0.849341    0.24571545  1.71056173  0.48150887]


In [14]:
print(a.shape)

(5,)


In [16]:
print(a.T)

[ 0.17490732 -0.849341    0.24571545  1.71056173  0.48150887]


In [17]:
print(np.dot(a, a.T))

3.9702209955775816


In [18]:
a = np.random.randn(5,1)
print(a)

[[-0.09659417]
 [-1.25162822]
 [ 0.62544626]
 [ 0.22377047]
 [-0.90681386]]


In [19]:
print(a.T)

[[-0.09659417 -1.25162822  0.62544626  0.22377047 -0.90681386]]


In [22]:
print(np.dot(a, a.T))

[[ 0.00933043  0.12089999 -0.06041446 -0.02161492  0.08759293]
 [ 0.12089999  1.5665732  -0.7828262  -0.28007743  1.13499382]
 [-0.06041446 -0.7828262   0.39118303  0.1399564  -0.56716334]
 [-0.02161492 -0.28007743  0.1399564   0.05007322 -0.20291816]
 [ 0.08759293  1.13499382 -0.56716334 -0.20291816  0.82231137]]


In [18]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b